/*
CTexture

      CTexture is independent primatter, own the id itself, but one CTexture object can be reference of various
	  CMaterial objects which maybe generate different texture unit id for the CTexture object. So, CTexture need
	  a host member which point the material relation with it.
	  ??? How be the host set when different material use the reference of same one texture.

Author: Zhen Yi

Created Date: Feb.26, 2023

Version: 0.2.0 Alpha

*/




#ifndef _FW_TEXTURE_
#define _FW_TEXTURE_

#include "GL/glew.h"
#include "CPrimatter.h"
#include"FWEngineCoreExport.h"


namespace FW
{

	class CTextureUnit;
	class DLLCOAPI CTexture : public CPrimatter
	{
	private:
		typedef enum { EP_RGB = 3, EP_RGBA, EP_UNKNOWN }EPIXELTYPE;

	public:
		CTexture(CConstruct* pHost);
		CTexture(const char* pszName, CConstruct* pHost);

		virtual ~CTexture();

		bool Create(unsigned char* pColorBuffer, int stride, int width, int height);

	public:
		//Inherited from CPrimatter
		virtual bool Initialize(const char* pszName, const char* pszNamePathAndFile);
		virtual bool Clone(CPrimatter* pPmt);

	//attribute
	public:
		CTextureUnit* host() { return (CTextureUnit*)m_pHost; }
		//void setHost(CTextureUnit* pHost) { m_pHost = pHost; }

		GLuint idTexture() { return m_uTextureId; }

		int width() { return m_nWidth; }
		int height() { return m_nHeight; }


	private:
		EPIXELTYPE m_ePixelType;

		// be generated by OpenGLES interface function.
		GLuint m_uTextureId;

		int m_nWidth;
		int m_nHeight;

	};

}

#endif // !_FW_TEXTURE_
